language: python
python:
  - "2.6"
  - "2.7"
before_script: sudo apt-get install pychecker pylint pep8 rpm python-rpm
install:
  - pip install -r requirements.txt --use-mirrors
  - pyb --debug install_dependencies
script: "pyb --debug analyze publish"
notifications:
  email:
    - arne.hilmann@immobilienscout24.de
    - michael.gruber@immobilienscout24.de

